[build]
  command = "npm run build"
  functions = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3005

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
